import * as Joi from 'joi';

export const validationSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'production'),
  PORT: Joi.number().default(3000),
  SUPABASE_URL: Joi.string().uri().required(),
  SUPABASE_PUBLISHABLE_KEY: Joi.string().required(),
  SUPABASE_WEBHOOK_SECRET: Joi.string().required(),
  R2_ACCOUNT_ID: Joi.string().required(),
  R2_ACCESS_KEY_ID: Joi.string().required(),
  R2_SECRET_ACCESS_KEY: Joi.string().required(),
  R2_BUCKET_NAME: Joi.string().required(),
  R2_PUBLIC_URL: Joi.string().uri().required(),
  OPENAI_API_KEY: Joi.string().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PORT: Joi.number().default(6379),
  BULLMQ_CONCURRENCY: Joi.number().default(5),
  FRONTEND_URL: Joi.string().uri().required(),
  THROTTLER_API_IP_TTL: Joi.number().default(900),
  THROTTLER_API_IP_LIMIT: Joi.number().default(300),
  THROTTLER_API_USER_TTL: Joi.number().default(900),
  THROTTLER_API_USER_LIMIT: Joi.number().default(100),
  THROTTLER_AI_IP_TTL: Joi.number().default(3600),
  THROTTLER_AI_IP_LIMIT: Joi.number().default(50),
  THROTTLER_AI_USER_TTL: Joi.number().default(3600),
  THROTTLER_AI_USER_LIMIT: Joi.number().default(10),
});
